HealthDesease/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from healthapp.views import *
# from .api import router

urlpatterns = [
    # path('api/sensoviz/', include(router.urls)),
    path('admin/', admin.site.urls),
    path('', Home, name="home"),
    path('patient_home', User_Home,name="patient_home"),
    path('doctor_home', Doctor_Home,name="doctor_home"),
    path('admin_home', Admin_Home,name="admin_home"),
    path('about', About,name="about"),
    path('contact', Contact,name="contact"),
    path('gallery', Gallery,name="gallery"),
    path('login', Login_User,name="login"),
    path('login_admin', Login_admin,name="login_admin"),
    path('signup', Signup_User,name="signup"),
    path('logout', Logout,name="logout"),
    path('change_password', Change_Password,name="change_password"),
    # path('prdict_heart_disease', prdict_heart_disease,name="prdict_heart_disease"),
    path('add_heartdetail', add_heartdetail,name="add_heartdetail"),
    path('view_search_pat', view_search_pat,name="view_search_pat"),

    path('view_doctor', View_Doctor,name="view_doctor"),
    path('add_doctor', add_doctor,name="add_doctor"),
    path('change_doctor/<int:pid>/', add_doctor,name="change_doctor"),
    path('view_patient', View_Patient,name="view_patient"),
    path('view_feedback', View_Feedback,name="view_feedback"),
    path('edit_profile', Edit_My_deatail,name="edit_profile"),
    path('profile_doctor', View_My_Detail,name="profile_doctor"),
    path('sent_feedback', sent_feedback,name="sent_feedback"),

    path('delete_searched/<int:pid>', delete_searched, name="delete_searched"),
    path('delete_doctor<int:pid>', delete_doctor, name="delete_doctor"),
    path('assign_status<int:pid>', assign_status, name="assign_status"),
    path('delete_patient<int:pid>', delete_patient, name="delete_patient"),
    path('delete_feedback<int:pid>', delete_feedback, name="delete_feedback"),
    path('predict_desease/<str:pred>/<str:accuracy>/', predict_desease, name="predict_desease"),

    path('add_genralhealth', add_genralhealth, name="add_genralhealth"),

    path('search_blood', search_blood, name="search_blood"),
    path('donate_blood', donate_blood, name="donate_blood"),

    path('request_blood', request_blood, name="request_blood"),
    path('donator_blood', donator_blood, name="donator_blood"),

    path('change_status/<int:pid>/', change_status, name="change_status")

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

healthapp/models.py
from operator import mod
from pyexpat import model
from re import M
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
DOCTOR_STATUS = ((1, 'Authorize'), (2, 'UnAuthorize'))

class Patient(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    contact = models.CharField(max_length=100, null=True)
    address = models.CharField(max_length=100, null=True)
    dob = models.DateField(null=True)
    image = models.FileField(null=True)

    def __str__(self):
        return self.user.username

class Doctor(models.Model):
    status = models.IntegerField(DOCTOR_STATUS, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    contact = models.CharField(max_length=100, null=True)
    address = models.CharField(max_length=100, null=True)
    category = models.CharField(max_length=100, null=True)
    doj = models.DateField(null=True)
    dob = models.DateField(null=True)
    image = models.FileField(null=True)

    def __str__(self):
        return self.user.username

class Admin_Helath_CSV(models.Model):
    name = models.CharField(max_length=100, null=True)
    csv_file = models.FileField(null=True, blank=True)

    def __str__(self):
        return self.name

class Search_Data(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, null=True)
    prediction_accuracy = models.CharField(max_length=100,null=True,blank=True)
    result = models.CharField(max_length=100,null=True,blank=True)
    values_list = models.CharField(max_length=100,null=True,blank=True)
    predict_for = models.CharField(max_length=100,null=True,blank=True)
    created = models.DateTimeField(auto_now=True,null=True)

    def __str__(self):
        return self.patient.user.username

class Feedback(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    messages = models.TextField(null=True)
    date = models.DateField(auto_now=True)

    def __str__(self):
        return self.user.user.username

class GeneralHealthProblem(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name

class Blood_Donation(models.Model):
    status = models.CharField(max_length=100, null=True, blank=True)
    user = models.ForeignKey(Patient, on_delete=models.CASCADE, null=True, blank=True)
    blood_group = models.CharField(max_length=100, null=True, blank=True)
    place = models.CharField(max_length=100, null=True, blank=True)
    purpose = models.CharField(max_length=100, null=True, blank=True)
    created = models.DateTimeField(auto_now=True,null=True)
    active = models.BooleanField(null=True, blank=True, default=False)

    def __str__(self):
        return self.user.user.username

healthapp/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import *

class DoctorForm(forms.ModelForm):
    class Meta:
        model = Doctor
        exclude = ('status', 'user', 'dob', 'doj')

healthapp/templates/add_genralhealth.html
{% extends 'index.html' %}
{% load static %}
{% block body %}
	<!-- register -->



	<section class="logins py-5">
		<div class="container py-xl-5 py-lg-3">
			{% if predictiondata %}

			<div class="title-section mb-md-5 mb-4">
				<h6 class="w3ls-title-sub"></h6>
				<h3 class="w3ls-title text-uppercase text-dark font-weight-bold">Result After Prediction</h3>
			</div><hr/>

			<div class="form-group row">
				<div class="col-md-6" style="border:1px solid black;padding:6px;background:blue;color:white">
					<label><b>Model Name</b></label>
				</div>
				<div class="col-md-6" style="border:1px solid black;padding:6px;background:blue;color:white">
					<label><b>Prediction Output</b></label>
				</div>
				{% for i, j in predictiondata.items %}
				<div class="col-md-6" style="border:1px solid black;padding:6px">
					<label><b>{{i}}</b></label>
				</div>
				<div class="col-md-6" style="border:1px solid black;padding:6px">
					<label>{{j}}</label>
				</div>
				{% endfor %}
			
			</div>

			{% else %}



			
			<div class="title-section mb-md-5 mb-4">
				<h6 class="w3ls-title-sub"></h6>
				<h3 class="w3ls-title text-uppercase text-dark font-weight-bold">Select Your Problem</h3>
			</div><hr/>
			<div class="login px-sm-12" style="width:100%">
				<form action="" method="post" enctype="multipart/form-data">
					{% csrf_token %}
					<div class="form-group row">

						{% for i in alldisease %}
						<div class="col-md-3" style="border:1px solid black;padding:6px">
							<label>{{i}}</label>
							<input type="radio" name="{{i}}" style="width:30px;height:15px">
						</div>
						{% endfor %}
					
					</div>
					<button type="submit" class="btn btn-primary submit mt-4">Send Data</button>
				</form>
			</div>
			{% endif %}
		</div>
	</section>
	<!-- //register -->

{% endblock %}

healthapp/templates/admin_home.html
{% extends 'index.html' %}
{% load static %}
{% block body %}

<style>
.glow {
  font-size: 80px;
  color: #fff;
  text-align: center;
  -webkit-animation: glow 1s ease-in-out infinite alternate;
  -moz-animation: glow 1s ease-in-out infinite alternate;
  animation: glow 1s ease-in-out infinite alternate;
}

@-webkit-keyframes glow {
  from {
    text-shadow: 0 0 10px #fff, 0 0 20px #fff, 0 0 30px #e60073, 0 0 40px #e60073, 0 0 50px #e60073, 0 0 60px #e60073, 0 0 70px #e60073;
  }

  to {
    text-shadow: 0 0 20px #fff, 0 0 30px #ff4da6, 0 0 40px #ff4da6, 0 0 50px #ff4da6, 0 0 60px #ff4da6, 0 0 70px #ff4da6, 0 0 80px #ff4da6;
  }
}

/* Rounded border */
hr.rounded {
  border-top: 8px solid lightblue;
  border-radius: 5px;
}

.prjdiv:hover{
transform:translateY(-10px)
}
div .container1{

width:100%;
background-color:white;
border-radius:8px;
}
h2, h4{
 padding:10Px;
}

</style>


<div class="container-fluid" style="margin-top:8%;width:100%">
    <div class="container-fluid">
        <h1 align="center" style="font-weight:bold;font-family:roman">ADMIN DASHBOARD</h1><hr/>
    </div>
             <div class="row">

			        <div class="col-md-3" ><a href="{% url 'view_doctor' %}">
						<div style="margin:1%;padding:10px;background:Darkslategrey;color:white;">
						<h3 style="font-weight:bold;font-size:35px">{{doc}}</h3><br/>
						        <h4 style="font-weight:bold;">Total Doctors</h4>
						        <p style="color:black">All access are given .</p>
							</div></a>
					</div>


					<div class="col-md-3" ><a href="{% url 'view_patient' %}">
						    <div style="padding:10px;margin:1%;background:Green;color:white;">
						        <h3 style="font-weight:bold;font-size:35px">{{pat}}</h3><br/>
						        <h4 style="font-weight:bold;">Total Users</h4>
						        <p style="color:black">All access are given .</p>
							</div></a>
							</div>


					<div class="col-md-3" >
						<a href="{% url 'view_feedback' %}">
					<div style="padding:10px;margin:1%;background:Red;color:white;">
								<h3 style="font-weight:bold;font-size:35px">{{feed}}</h3><br/>
						        <h4 style="font-weight:bold;">Total Feedback</h4>
						        <p style="color:black">All access are given .</p>
					</div></a>
					</div>

						<div class="col-md-3" >
							<a href="{% url 'view_search_pat' %}">
								<div style="padding:10px;margin:1%;background:Lime;color:white;">
						        <h3 style="font-weight:bold;font-size:35px">{{dis}}</h3><br/>
						        <h4 style="font-weight:bold;">Searched Quantity</h4>
						        <p style="color:black">All access are given .</p>
</a>
							</div>
						</div>

             </div>
		</div>

	<div>
      <!--<div class="container">

        <div class="row pt-5 mt-5 text-center">
          <div>
            <p style = "font-size : 30pt ; color : #FF0000 ; font-weight : bold">

            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All Rights Reserved <span style = "color : brown">|</span> <span style = "color : #006400">This website is made with <i class="fas fa-heart icon-heart text-warning" aria-hidden="true"></i> by </span><a class= "glow" href="#" target="_blank" >Harish Panjwani</a>

            </p>
          </div>

        </div>
      </div>-->

    </div>
{% endblock %}

healthapp/templates/assign_status.html
{% extends 'index.html' %}
{% load static %}
{% block body %}
<style>
    fieldset{
    color:black;
    }
</style>
<div class="container" style="margin-top:5%;margin-bottom:5%">
    <div class="row">
        <div  class="col-md-12">
                <h2 style="margin-top:5%;background:#262626;padding:19px;color:white">ASSIGN STATUS
                </h2>
<form id="loginForm" action="#" method="post" style="width:100%" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset id="body">
        <div class="row">
          <div class="col-md-12">
                <fieldset>
                    <label for="email" style="color:black;">Username</label><br>
                    <input style="height:33px;width:100%" type="text" name="uname" id="email" value="{{prod.user.username}}" style="height:33px;" readonly>
                </fieldset>
          </div>
          <div class="col-md-12">
                <fieldset>
                    <label for="email" style="color:black;">Status</label>
                    <select name="stat" class="form-group" style="height:33px;width:100%">
                        <option>----Select Status----</option>
                        <option value="Accept">Accept</option>
                        <option value="Reject">Reject</option>
                    </select>
                </fieldset>
          </div>
        </div>
    <button class="btn btn-danger" type="submit">Assign Status</button>
    </fieldset>
    </form>
    </div>

</div>

</div>

{% if terror %}
<script>
    alert('Assigned Status successfully');
    window.location = "{% url 'view_doctor' %}";
</script>
{% endif %}

{% endblock %}

healthapp/templates/doctor_home.html
{% extends 'index.html' %}
{% load static %}
{% block body %}
<div class="container-fluid" style="margin-top:10%;margin-bottom:2%;width:100%">
    <h2 align="center" style="font-weight:bold;font-family:roman">DOCTOR DASHBORAD</h2><hr/>
    <img src="{% static 'img/healthcare.jpg' %}" style="width:100%;height:500px">
</div>

{% endblock %}

healthapp/templates/index copy.html
<!DOCTYPE html>
{% load static %}
<html lang="zxx">

<head>
	<title>Heart Disease Prediction System</title>
	<!-- Meta tag Keywords -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="UTF-8" />
	<meta name="keywords" />
	<script>
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
	</script>
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<!-- Bootstrap-Core-CSS -->
	<link href="{% static 'css/css_slider.css' %}" type="text/css" rel="stylesheet" media="all">
	<!-- banner slider -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />
	<!-- Style-CSS -->
	<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
	<!-- Font-Awesome-Icons-CSS -->
	<!-- //Custom-Files -->

	<!-- Web-Fonts -->
	<link href="//fonts.googleapis.com/css?family=Quicksand:300,400,500,700" rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Mukta:200,300,400,500,600,700,800&amp;subset=devanagari,latin-ext" rel="stylesheet">
<style>	<!-- //Web-Fonts -->
.li2{
	border:1px solid red;
	padding:8px;
	}
</style>

<link rel='stylesheet' type='text/css' href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
<link rel='stylesheet' type='text/css' href="https://cdn.datatables.net/buttons/1.6.2/css/buttons.dataTables.min.css">

<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.html5.min.js"></script>

<script>
$(document).ready(function() {
    $('#example').DataTable( {
        dom: 'Bfrtip',
        buttons: [
            'copyHtml5',
            'excelHtml5',
            'csvHtml5',
            'pdfHtml5'
        ]
    } );
} );
</script>
</head>

<body>
	<!-- main -->
	<div id="home" style="margin-bottom:2%">
		<!-- top header -->
		<header>
			<div class="top-bar py-3">
				<div class="container">
					<div class="row">
						<div class="col-xl-6 col-lg-6 col-md-8 top-social-agile text-lg-left text-center">
							<div class="row">
								<div class="col-5 header-top_w3layouts">
									<p class="text-bl">
										<span class="fa fa-map-marker mr-2"></span>Indrapuri Sec-C, Bhopal
									</p>
								</div>
								<div class="col-3 header-top_w3layouts">
									<p class="text-bl">
										<span class="fa fa-phone mr-2"></span>+1 000263676
									</p>
								</div>
								<!-- social icons -->
								<ul class="col-4 top-right-info">
									<li>
										<a href="#">
											<span class="fa fa-facebook-f"></span>
										</a>
									</li>
									<li class="mx-3">
										<a href="#">
											<span class="fa fa-twitter"></span>
										</a>
									</li>
									<li>
										<a href="#">
											<span class="fa fa-google-plus"></span>
										</a>
									</li>
									<li class="ml-3">
										<a href="#">
											<span class="fa fa-pinterest-p"></span>
										</a>
									</li>
								</ul>
								<!-- //social icons -->
							</div>
						</div>
						<div class="col-xl-7 col-lg-6 col-md-4 top-social-agile text-md-right text-center mt-md-0 mt-2">
							<div class="row">
								<div class="offset-xl-6 offset-lg-4">
								</div>
								<div class="col-xl-3 col-lg-4 col-6 top-w3layouts p-md-0 text-right">
									<!-- login -->
									<a href="login.html" class="login-button-2 text-uppercase text-bl">
										</a>
									<!-- //login -->
								</div>
								<div class="col-xl-3 col-lg-4 col-6 header-w3layouts text-md-right text-left">
									<!-- register -->
									<a href="register.html" class="login-button-2 text-uppercase text-bl">
										</a>
									<!-- //register -->
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</header>
		<!-- //top header -->

		<!-- second header -->
		<div class="main-top" style="background:Green">
			<div class="container-fluid">
				<div class="header d-md-flex justify-content-between align-items-center py-3">
					<!-- logo -->
					<div id="logo" style="margin-left:13%">
						<h1>
							<a href="index.html">
								<span class="fa fa-user-md mr-2"></span>
								<span class="logo-sp">Heart Disease</span> Prediction
							</a>
						</h1>
					</div>
					<!-- //logo -->
					<!-- nav -->
					{% if request.user.is_staff %}
					<div class="nav_w3ls" style="margin-right:4%">
						<nav>
							<label for="drop1" class="toggle">Menu</label>
							<input type="checkbox" id="drop1" />
							<ul class="menu" style="padding:15px;width:100%">

								<li class="mx-lg-4 mx-md-3 my-md-0 my-2"><a href="{% url 'admin_home' %}" class="active">Home</a></li>

								<li>
									<label for="drop-2" class="toggle toogle-2"> <span class="fa fa-angle-down" aria-hidden="true"></span>
									</label>
									<a href="#"> Doctor <span class="fa fa-angle-down" aria-hidden="true"></span></a>
									<ul style="margin-top:2%;width:40%;margin-right:0%">
										<li style="width:100%;"><a href="/add_doctor" class="drop-text">Add Doctor</a></li>
										<li style="width:100%;"><a href="/view_doctor" class="drop-text">View Doctor</a></li>
									</ul>
								</li>



								<li class="mx-lg-4 mx-md-3 my-md-0 my-2"><a href="/view_patient">Patient</a></li>
								<li class="mx-lg-4 mx-md-3 my-md-0 my-2">
									<a href="/view_search_pat">Searched Data</a></li>
								<li><a href="/view_feedback">Feedback</a></li>

							</ul>
						</nav>
					</div>
					<div class="nav_w3ls" style="margin-right:3%">

						<nav>
							<label for="drop2" class="toggle">Menu</label>
							<input type="checkbox" id="drop2" />
							<ul class="menu">
								<li class="mx-lg-4 mx-md-3 my-md-0 my-2" style="background:red;padding:8px">
									<!-- First Tier Drop Down -->
									<label for="drop-2" class="toggle toogle-2"> <span class="fa fa-angle-down" aria-hidden="true"></span>
									</label>
									<a href="#"><i class="fa fa-user"></i> {{request.user.username}} <span class="fa fa-angle-down" aria-hidden="true"></span></a>
									<ul style="margin-top:10%;width:80%;margin-right:5%">
										<li style="width:100%;"><a href="{% url 'change_password' %}" class="drop-text">Password</a></li>
										<li style="width:100%;"><a href="{% url 'logout' %}" class="drop-text">Logout</a></li>
									</ul>
								</li>



							</ul>
						</nav>
					</div>

					{% elif request.user.patient_set.all.0 %}
					<div class="nav_w3ls" style="margin-left:5%;font-weight:bold">
						<nav>
							<label for="drop3" class="toggle">Menu</label>
							<input type="checkbox" id="drop3" />
							<ul class="menu" style="padding:15px;width:100%">
								<li><a href="{% url 'patient_home' %}" class="active">Home</a></li>
								<li class="mx-lg-4 mx-md-3 my-md-0 my-2"><a href="/add_heartdetail">Predict</a></li>
								<li class="mx-lg-4 mx-md-3 my-md-0 my-2"><a href="/profile_doctor">My Detail</a></li>
								<li class="mx-lg-4 mx-md-3 my-md-0 my-2"><a href="/sent_feedback">Feedback</a></li>
								<li><a href="/view_search_pat">History</a></li>
							</ul>
						</nav>
					</div>
					<div class="nav_w3ls" style="margin-right:3%">

						<nav>
							<label for="drop4" class="toggle">Menu</label>
							<input type="checkbox" id="drop4" />
							<ul class="menu">
								<li class="mx-lg-4 mx-md-3 my-md-0 my-2" style="background:red;padding:8px">
									<!-- First Tier Drop Down -->
									<label for="drop-3" class="toggle toogle-3"> <span class="fa fa-angle-down" aria-hidden="true"></span>
									</label>
									<a href="#"><i class="fa fa-sign-in"></i> Hello,{{request.user.username}} <span class="fa fa-angle-down" aria-hidden="true"></span></a>
									<ul style="margin-top:8%;width:80%;margin-right:5%">
										<li style="width:100%;"><a href="{% url 'change_password' %}" class="drop-text"> Password</a></li>
										<li style="width:100%;"><a href="{% url 'logout' %}" class="drop-text"> Logout</a></li>
									</ul>
								</li>
							</ul>
						</nav>
					</div>
					{% elif request.user.doctor_set.all.0 %}
					<div class="nav_w3ls" style="margin-right:4%">
						<nav>
							<label for="drop5" class="toggle">Menu</label>
							<input type="checkbox" id="drop5" />
							<ul class="menu" style="padding:15px;width:100%">
								<li><a href="{% url 'doctor_home' %}" class="active">Home</a></li>
								<li class="mx-lg-4 mx-md-3 my-md-0 my-2">
									<a href="/profile_doctor">My Detail</a></li>
								<li class="mx-lg-4 mx-md-3 my-md-0 my-2">
									<a href="view_search_pat">Searched Data</a></li>

							</ul>
						</nav>
					</div>
					<div class="nav_w3ls" style="margin-right:3%">

						<nav>
							<label for="drop6" class="toggle">Menu</label>
							<input type="checkbox" id="drop6" />
							<ul class="menu">
								<li class="mx-lg-4 mx-md-3 my-md-0 my-2" style="background:red;padding:8px">
									<!-- First Tier Drop Down -->
									<label for="drop6" class="toggle toogle-2"> <span class="fa fa-angle-down" aria-hidden="true"></span>
									</label>
									<a href="#"><i class="fa fa-user"></i> {{request.user.username}} <span class="fa fa-angle-down" aria-hidden="true"></span></a>
									<ul style="margin-top:10%;width:80%;margin-right:5%">
										<li style="width:100%;"><a href="{% url 'change_password' %}" class="drop-text">Password</a></li>
										<li style="width:100%;"><a href="{% url 'logout' %}" class="drop-text">Logout</a></li>
									</ul>
								</li>



							</ul>
						</nav>
					</div>
					{% else %}
					<div class="nav_w3ls" style="margin-right:4%">
						<nav>
							<label for="drop7" class="toggle">Menu</label>
							<input type="checkbox" id="drop7" />
							<ul class="menu" style="padding:15px;width:100%">
								<li><a href="{% url 'home' %}" class="active">Home</a></li>
								<li class="mx-lg-4 mx-md-3 my-md-0 my-2">
									<a href="{% url 'about' %}">About Us</a></li>
								<li><a href="{% url 'gallery' %}">Gallery</a></li>

								<li style="padding-left:20px"><a href="{% url 'contact' %}">Contact Us</a></li>
							</ul>
						</nav>
					</div>
					<div class="nav_w3ls" style="margin-right:3%">

						<nav>
							<label for="drop" class="toggle">Menu</label>
							<input type="checkbox" id="drop" />
							<ul class="menu">
								<li class="mx-lg-4 mx-md-3 my-md-0 my-2" style="background:red;padding:8px">
									<!-- First Tier Drop Down -->
									<label for="drop-2" class="toggle toogle-2"> <span class="fa fa-angle-down" aria-hidden="true"></span>
									</label>
									<a href="#"><i class="fa fa-sign-in"></i> Login <span class="fa fa-angle-down" aria-hidden="true"></span></a>
									<ul style="margin-top:10%;width:80%;margin-right:5%">
										<li style="width:100%;"><a href="{% url 'login_admin' %}" class="drop-text">Admin</a></li>
										<li style="width:100%;"><a href="{% url 'login' %}" class="drop-text">User</a></li>
									</ul>
								</li>



							</ul>
						</nav>
					</div>
					{% endif %}


					<!-- //nav -->
				</div>
			</div>
		</div>
		<!-- //second header -->

		<!-- banner -->
		{% block body %}
		{% endblock %}
		<!-- //banner -->
	</div>
	<!-- //main -->


	<!-- footer bottom -->
	<!-- copyright -->
	<div class="copy-w3pvt" style="background:green;color:white">
		<div class="container py-3">
			<div class="row">
				<div class="col-lg-7 w3ls_footer_grid1_left text-lg-left text-center">
					<p style="color:white">&copy; 2020 Heart Disease Prediction. All rights reserved | Design by
						Pankaj Panjwani</a>
					</p>
				</div>
				<div class="col-lg-5 w3ls_footer_grid_left1_pos text-lg-right text-center mt-lg-0 mt-2">
					<ul style="color:white">
						<li>
							<a href="#" style="color:white" class="facebook">
								<span class="fa fa-facebook-f mr-2"></span>Facebook</a>
						</li>
						<li class="mx-3">
							<a href="#" style="color:white" class="twitter">
								<span class="fa fa-twitter mr-2"></span>Twitter</a>
						</li>
						<li>
							<a href="#" style="color:white" class="google">
								<span class="fa fa-google-plus mr-2"></span>Google Plus</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<!-- //copyright -->
	<!-- //footer bottom -->
	<!-- move top icon -->
	<a href="#home" style="color:white" class="move-top text-center"></a>
	<!-- //move top icon -->

</body>

</html>